version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gt-lambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jbjkzibjwsu5"
s3_prefix = "gt-lambdas"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

